  0         LOADL        5
  1         STORE        0[SB]
  2         LOAD         0[SB]
  3         LOADL        3
  4         CALL         add     
  5         CALL         putintnl
  6         LOADL        2
  7         CALL         newarr  
  8         HALT   (0)   
